kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
  namespace: hackathon
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
